name: Merge Scheduled Pull Requests
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # Run this workflow daily at 1:00 AM, [using tz set below]
    - cron: 00 01 * * *

jobs:
  merge_scheduled_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          # ----------------------------------------------------------------
          # Code4Lib messaging most often states end dates in 'pacific time'
          # Pacific Standard Time, Los Angeles, CA
          # ----------------------------------------------------------------
          time_zone: "America/Los_Angeles"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}